version: 2
jobs:
  build_and_test:
    working_directory: /app
    docker:
      - image: docker:17.05.0-ce-git
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Install dependencies
          command: |
            apk add --no-cache \
              py-pip=9.0.0-r1
            pip install \
              docker-compose==1.12.0 \
              awscli==1.11.76
      - restore_cache:
          keys:
            - v1-{{ .Branch }}
          paths:
            - /caches/app.tar
      - run:
          name: Load Docker image layer cache
          command: |
            set +o pipefail
            docker load -i /caches/app.tar | true
      - run:
          name: Build application Docker image
          command: |
            docker build -f Dockerfile.dev --cache-from=app -t prabhakarmaity/docker-react:$CIRCLE_SHA1 .
      - run:
          name: Save Docker image layer cache
          command: |
            mkdir -p /caches
            docker save -o /caches/app.tar prabhakarmaity/docker-react:$CIRCLE_SHA1
      - save_cache:
          key: v1-{{ .Branch }}-{{ epoch }}
          paths:
            - /caches/app.tar
      - run:
          name: Run tests
          command: |
            docker run -e CI=true prabhakarmaity/docker-react:$CIRCLE_SHA1 npm run test:ci
  deploy:
    working_directory: /app
    machine:
      image: ubuntu-2004:202104-01
      docker_layer_caching: true    # default - false
    docker:
      - image: docker:17.05.0-ce-git
    steps:
      - setup_remote_docker
      - run:
          name: Installing deployment dependencies
          working_directory: /
          command: |
            apk update
            apk add --update python3-pip
            apk add python3-pip python3-dev build-essential
            pip3 install awsebcli
      - run:
          name: Deploying
          command: eb deploy docker-react-app



workflows:
  version: 2
  build_and_test:
    jobs:
      - build_and_test
  deploy:
    jobs:
      - build_and_test
      - deploy:
          requires:
            - build_and_test
          filters:
            branches:
              only:
                - master
