version: 2
jobs:
  build:
    working_directory: /app
    docker:
      - image: docker:17.05.0-ce-git
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Install dependencies
          command: |
            apk add --no-cache \
              py-pip=9.0.0-r1
            pip install \
              docker-compose==1.12.0 \
              awscli==1.11.76
      - restore_cache:
          keys:
            - v1-{{ .Branch }}
          paths:
            - /caches/app.tar
      - run:
          name: Load Docker image layer cache
          command: |
            set +o pipefail
            docker load -i /caches/app.tar | true
      - run:
          name: Build application Docker image
          command: |
            docker build -f Dockerfile.dev --cache-from=app -t prabhakarmaity/docker-react:$CIRCLE_SHA1 .
      - run:
          name: Save Docker image layer cache
          command: |
            mkdir -p /caches
            docker save -o /caches/app.tar prabhakarmaity/docker-react:$CIRCLE_SHA1
      - save_cache:
          key: v1-{{ .Branch }}-{{ epoch }}
          paths:
            - /caches/app.tar
  test:
    working_directory: /app
    docker:
      - image: docker:17.05.0-ce-git
    steps:
      - run:
        name: Run tests
        command: |
          docker run -e CI=true prabhakarmaity/docker-react:$CIRCLE_SHA1 npm run test:ci
  deploy:
    working_directory: /app
    docker:
      - image: docker:17.05.0-ce-git
    steps:
      - run:
          name: Installing deployment dependencies
          working_directory: /
          command: |
            sudo apt-get -y -qq update
            sudo apt-get install python-pip python-dev build-essential
            sudo pip install awsebcli --upgrade
      # !!! This runs a deployment
      - run:
          name: Deploying
          command: eb deploy docker-react-app


workflows:
  version: 2
  build_and_test:
    jobs:
      - build
      - test:
          requires:
            - build
  deploy:
    jobs:
      - deploy:
          requires:
            - build
            - test
          filters:
            branches:
              only:
                - master

